# This depends on the following env vars to be set in Gitlab:
#   https://gitlab.com/mozmeao/lumbergh/settings/ci_cd
# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY
# DMS DeadMansSnitch URL
# DMS_BLOG_FETCH DeadMansSnitch URL for successful blog fetches

variables:
  STAGE_BUCKET_PATH: s3://mozilla-careers-stage
  STAGE_ESCAPED_SITE_URL: https:\/\/careers.allizom.org
  PROD_BUCKET_PATH: s3://mozilla-careers
  PROD_ESCAPED_SITE_URL: https:\/\/careers.mozilla.org

deploy stage:
  stage: deploy
  tags:
  - oregon-b-shell
  variables:
    BUCKET_PATH: ${STAGE_BUCKET_PATH}
    ESCAPED_SITE_URL: ${STAGE_ESCAPED_SITE_URL}
  only:
    refs:
    - master
    - issue-515
  script: ./bin/ci-mirror.sh

deploy prod:
  stage: deploy
  tags:
  - oregon-b-shell
  variables:
    BUCKET_PATH: ${PROD_BUCKET_PATH}
    ESCAPED_SITE_URL: ${PROD_ESCAPED_SITE_URL}
  only:
    refs:
    - prod
  script: ./bin/ci-mirror.sh
