sudo: false
language: python
python:
  - "2.7"
addons:
  postgresql: "9.4"
before_script:
  - createdb lumbergh_db
install:
  - pip install tox coveralls
env:
  - TOX_ENV=flake8
  - TOX_ENV=docs
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
deploy:
  - provider: script
    script: bin/deploy-travis.sh stage
    on:
      branch: sugardough
      repo: mozilla/lumbergh
      condition: $TOX_ENV = tests
  - provider: script
    script: bin/deploy-travis.sh prod
    on:
      tags: true
      repo: mozilla/lumbergh
      condition: $TOX_ENV = tests
